# ======================================================
# <             Compressed Blocks Plugin:              >
# <                 Configuration File                 >
# < https://github.com/Joffrey4/CompressedBlocksPlugin >
# ======================================================

# This configuration file was generated in v1.4.
# Please respect the indentation (2 spaces).

# If any change are made in a future version, you will need to
# add the missing parameters on your own, or to generate a new
# configuration file by deleting this one.


# CRAFT: Enable and disable compression and/or un-compression crafts by setting "true" of "false":

Wood:
  Compressing: true
  Uncompressing: true

Plank:
  Compressing: true
  Uncompressing: true

Gravel:
  Compressing: true
  Uncompressing: true

Sand:
  Compressing: true
  Uncompressing: true

Stone:
  Compressing: true
  Uncompressing: true

Granite:
  Compressing: true
  Uncompressing: true

Diorite:
  Compressing: true
  Uncompressing: true

Andesite:
  Compressing: true
  Uncompressing: true

Dirt:
  Compressing: true
  Uncompressing: true

Cobblestone:
  Compressing: true
  Uncompressing: true

SoulSand:
  Compressing: true
  Uncompressing: true

Netherrack:
  Compressing: true
  Uncompressing: true


# LANGUAGES: Lore
# Use a common lore for all of your block by setting 'UseCommonLore' to true. You can also write
# specific lore for certain block by setting it to false, and by editing the detailed lore below.
# Use '&type' to write automatically the block type (ex 'Cobblestone' for Compressed Cobblestone).
# Lore modification is applied only to newly compressed block.

UseCommonLore: true
CommonLore:
  - 'A block that contain'
  - '9x &type !'

# DetailedLore:
#   Wood:
#     - 'Another lore specific'
#     - 'to the &type !'
#   Plank:
#   Gravel:
#   Sand:
#   RedSand
#   Stone:
#   Granite:
#   Diorite:
#   Andesite:
#   Dirt:
#   Cobblestone:
#   SoulSand:
#   Netherrack:


# LANGUAGES: Error messages

Lang:
# PlacingImpossible: Displayed when a player try to place a compressed block in the world.
  PlacingImpossible: 'You can not place a compressed block in the world !'

# FurnaceImpossible: Displayed when a player try to use a compressed block in a furnace.
  FurnaceImpossible: 'You can not use a compressed block in a furnace !'